// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package openapi

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      *int32  `json:"code,omitempty"`
	Component *string `json:"component,omitempty"`
	Msg       *string `json:"msg,omitempty"`
}

// Policy defines model for Policy.
type Policy struct {
	Name       string      `json:"name"`
	Statements []Statement `json:"statements"`
	Version    string      `json:"version"`
}

// PolicyId defines model for PolicyId.
type PolicyId struct {
	Id *string `json:"id,omitempty"`
}

// PolicyMatchesResponse defines model for PolicyMatchesResponse.
type PolicyMatchesResponse struct {
	Data    Matchesdata `json:"data"`
	Info    Information `json:"info"`
	Success bool        `json:"success"`
}

// Statement defines model for Statement.
type Statement struct {
	Actions  *[]string `json:"actions,omitempty"`
	Effect   *string   `json:"effect,omitempty"`
	Filter   *Filter   `json:"filter,omitempty"`
	Resource *string   `json:"resource,omitempty"`
	Sid      *string   `json:"sid,omitempty"`
}

// Filter defines model for filter.
type Filter struct {
	Equals *[]string `json:"equals,omitempty"`
	Like   *[]string `json:"like,omitempty"`
}

// Information defines model for information.
type Information struct {
	Name      string  `json:"name"`
	Timestamp float32 `json:"timestamp"`
	Version   string  `json:"version"`
}

// Match defines model for match.
type Match struct {
	Id   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Matchesdata defines model for matchesdata.
type Matchesdata []Match

// SavePolicyJSONBody defines parameters for SavePolicy.
type SavePolicyJSONBody Policy

// SavePolicyJSONRequestBody defines body for SavePolicy for application/json ContentType.
type SavePolicyJSONRequestBody SavePolicyJSONBody
